name: Deploy to EC2 and Run Docker

on:
  workflow_run:
    workflows: ["Build and Dockerize"]
    types:
      - completed

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Workflow received completion status from Build and Dockerize."

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: check-status
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EC2_PUBLIC_KEY: ${{ secrets.EC2_PUBLIC_KEY }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Check environment variables (optional for debugging purposes)
      - name: Check environment variables
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "EC2_PUBLIC_KEY=${{ secrets.EC2_PUBLIC_KEY }}"

      # Step 3: SSH into EC2 Instance and Deploy the Docker image
      - name: SSH into EC2 Instance and Deploy Docker Image
        run: |
          EC2_IP=${{ secrets.EC2_PUBLIC_IP }}  # Manually set your EC2 instance's public IP
          echo "Connecting to EC2 instance at $EC2_IP"
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.EC2_SSH_PRIVATE_KEY }}" ec2-user@$EC2_IP <<EOF
            # Install Docker and Docker Compose
            sudo yum update -y
            sudo amazon-linux-extras install docker
            sudo service docker start
            sudo usermod -a -G docker ec2-user

            # Pull Docker image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/deploymysql:latest

            # Clone docker-compose repository
            git clone git clone https://github.com/iumar288/DockerCompose
            cd DockerCompose/mysql

            # Run Docker Compose to deploy
            docker-compose up -d
          EOF
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
